services:

  find-directions:
    container_name: find-directions
    image: find-directions
    depends_on:
      - john-mariadb
      - john-redis
    ports:
      - 80:8080
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATA_REDIS_HOST=${SPRING_DATA_REDIS_HOST}
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}

    restart: always


  john-redis:
    container_name: john-redis
    image: redis:7.0
    ports:
      - 6379:6379

  john-mariadb:
    container_name: john-mariadb
    image: mariadb:11-ubi
    ports:
      - 3306:3306
    environment:
      - MARIADB_DATABASE=pharmacy-find-directions
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d



